version: "3"
services:
  # front:
  #   container_name: frontapp
  #   build:
  #     context: ./front
  #   ports:
  #     - '3000:3000'
  #     - '24678:24678' 
  #   volumes:
  #     - ./front:/front
  #   tty: true
  #   stdin_open: true
  #   environment:
  #     - CHOKIDAR_USEPOLLING=true

  server:
    container_name: serverapp
    build:
      context: ./server
    tty: true
    volumes:
      - ./server:/server
    working_dir: /server

  front-vue:
    container_name: frontvue
    build:
      context: ./front-vue
    ports:
      - '3000:3000'
      - '24678:24678' 
    volumes:
      - ./front-vue:/front-vue
    tty: true
    stdin_open: true
    environment:
      - CHOKIDAR_USEPOLLING=true


  nginx:
    image: nginx
    depends_on:
      - server
    container_name: server-nginx
    ports:
      - 80:80
    environment:
      - TZ=Asia/Tokyo
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
