version: "3"
services:
  # front:
  #   container_name: frontapp
  #   build:
  #     context: ./front
  #   ports:
  #     - '3000:3000'
  #     - '24678:24678' 
  #   volumes:
  #     - ./front:/front
  #   tty: true
  #   stdin_open: true
  #   environment:
  #     - CHOKIDAR_USEPOLLING=true

  server:
    container_name: serverapp
    build:
      context: ./server
    tty: true
    ports:
      - '5000:5000'
    volumes:
      - ./server:/server
    working_dir: /server

  # server-java:
  #   container_name: server-java
  #   build:
  #     context: ./server-java
  #   tty: true
  #   ports:
  #     - '9000:5000'
  #   volumes:
  #     - ./server-java:/server-java
  #   working_dir: /server-java


  front-vue:
    container_name: frontvue
    build:
      context: ./front-vue
    ports:
      - '3000:3000'
      - '24678:24678' 
    volumes:
      - ./front-vue:/front-vue
    tty: true
    stdin_open: true
    environment:
      - CHOKIDAR_USEPOLLING=true


  nginx:
    image: nginx
    depends_on:
      - server
    container_name: server-nginx
    ports:
      - 80:80
    environment:
      - TZ=Asia/Tokyo
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
